version: "3"

services:
  db:
    image: postgres
    expose:
      - "5432"

  redis:
    image: "redis:alpine"

  web:
    build: .
    command: bash -c "python /code/manage.py migrate --noinput && python /code/manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: celery -A core worker -l info
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    command: celery -A core beat -l info
    depends_on:
      - db
      - redis
